### ISSUE TITLE
How to install the web?

### ISSUE THREAD

**Issue by archonwang** [tobyqin/xmind2testlink#1]
@cicaday 

I installed it as follows
1. git clone https://github.com/tobyqin/xmind2testlink.git  /opt/xmind2testlink
2. cd /opt/xmind2testlink
3. python application.py

occured error
```
Traceback (most recent call last):
  File "application.py", line 7, in <module>
    from flask import Flask, request, redirect, url_for, send_from_directory, g
ImportError: No module named flask

```

How to config it?  Anythig I have missed? 
Thanks!!

**Comment by archonwang** [comment]
urr
I tried to install pip and Flask
but still with error, please check it

```
# python application.py 
Traceback (most recent call last):
  File "application.py", line 10, in <module>
    from src.xmind2testlink import convert_xmind
ImportError: No module named src.xmind2testlink
```

**Comment by ggqq** [comment]
please be patient, the web app is still under development. Now you can use command line version, it is available with pip.
```shell
pip install xmind2testlink
xmind2testlink /path/to/testcase.xmind
```

**Comment by ggqq** [comment]
I fixed the document for web, now the web app can be run, but UI still on the way.

**Comment by ggqq** [comment]
@archonwang the web app is almost done, please help a try.
