### ISSUE TITLE
中文文件名的xmind转化为xml，只有后缀xml

### ISSUE THREAD

**Issue by 1fengchen1** [tobyqin/xmind2testlink#19]
原因：因为使用的是werkzeug.utils import secure_filename，而secure_filename：The filename returned is an ASCII only string  for maximum portability.这就导致了中文名字会忽略掉，
建议：增加对中文文件名字的判断处理

**Comment by tobyqin** [comment]
谢谢发现这个问题，我的确没太考虑中文的问题，现在已经修复了，你拉一下最新的代码重新部署一下应该就可以了。

详情见 https://github.com/tobyqin/xmind2testlink/pull/23/files

**Comment by kakaaaluote** [comment]
Toby，好。
xmind 文件的文件名中包含中文时，中文还是会被过滤掉。
猜测原因是 secure_filename() 只会返回 ASCII，下面这个函数中，语句 `secured = re.sub('[^\w\d]+', '_', name)`  似乎不会生效。
`def check_file_name(name):
    secured = secure_filename(name)
    if not secured:
        secured = re.sub('[^\w\d]+', '_', name)  # only keep letters and digits from file name
        assert secured, 'Unable to parse file name: {}!'.format(name)
    return secured + '.xmind'`

**Comment by tobyqin** [comment]
@kakaaaluote 能否给个有问题的中文名例子？是不是全是中文字符？

**Comment by kakaaaluote** [comment]
非常抱歉，刚看到回复消息。
因为 xmind2testlink 部署在公司内网，xmind 文件无法取出来，也无法截图现象，所以我在此用文字描述一下过程。
1. 点击 **Click Here to Choose Your Xmind**，上传文件【南通_系统对接-项目_20190618_V1.0.xmind】；
2. 点击 **Convert To Testlink** 后，Preview 页面上看到【-_20190618_V1.0.xmind - Preview】。
此处的【-_20190618_V1.0.xmind】应该就是过滤了中文之后的部分。

**Comment by tobyqin** [comment]
了解了，现在就是这样设计的，中文会被过滤掉，这是一个简单粗暴的解决方案，因为xml上传后就没用了。

如果后续有思路了我看看怎么保留中文，如果你有好的方案也可以告诉我。

**Comment by kakaaaluote** [comment]
我使用的临时解决方案，是不使用 `secure_filename()` 方法，这样能够保留文件名中的中文，但是不知道是否会对其他的功能产生影响。
	def check_file_name(name):
		# secured = secure_filename(name)
                secured = name
		if not secured:
			secured = re.sub('[^\w\d]+', '_', name)  # only keep letters and digits from file name
			assert secured, 'Unable to parse file name: {}!'.format(name)
		return secured + '.xmind'
暂时就这样，等你有思路了看着改吧，我只是提出来这个问题。
PS：
这个工具非常好用，极大地减少了同事们花在用例设计上的时间，感谢。
