### ISSUE TITLE
2.0.6版本，默认测试方式错误

### ISSUE THREAD

**Issue by cscnkob** [tobyqin/xmind2testlink#27]
测试方式 : Unknown execution type code: 0，我查看了xml，你这里是
			<execution_type>
				
				
			</execution_type>

应该是
<execution_type><![CDATA[1]]></execution_type>

这样
![image](https://user-images.githubusercontent.com/5812388/51011650-4f392900-1594-11e9-9f04-c96a74019213.png)

**Comment by tobyqin** [comment]
你能给出合法的可选值吗？我们用的版本如果空的话就是manual。
我考虑一下用什么来标记，或者你给个建议。

初步想法：
- 默认情况下应该还是手动执行。
- 如果加了类似飞机或者某个maker，就是自动化执行。

**Comment by tobyqin** [comment]
好像我理解错了，等我查一下。

**Comment by cscnkob** [comment]
> * 默认情况下应该还是手动执行

默认手动执行即可，你这里是为空。
我看另外一个工具，他这里是采用数值，1就是手动 <execution_type><![CDATA[1]]></execution_type>

**Comment by tobyqin** [comment]
默认设置成1了，发了2.0.7版，你可以试一下。

**Comment by cscnkob** [comment]
> 默认设置成1了，发了2.0.7版，你可以试一下。

已解决，谢谢
