### ISSUE TITLE
建议增加子用例集功能

### ISSUE THREAD

**Issue by WinterDing** [tobyqin/xmind2testlink#33]
**Description:**
目前仅支持一级用例集，建议增加子用例集功能
![image](https://user-images.githubusercontent.com/13634462/54014464-c1567480-41b7-11e9-8903-ef1b660d7ea6.png)

**Comment by tobyqin** [comment]
你在子集的父集导入就行了。
在我们这边的实践里，一般集合的规模都挺大，如果一个case放一个suite执行起来也会很累。

另外如果要支持子集就得想办法在xmind里标记出来，没有很好的操作办法。故暂不考虑。
