### ISSUE TITLE
建议增加testlink2xmind功能

### ISSUE THREAD

**Issue by WinterDing** [tobyqin/xmind2testlink#34]
**Description:**
建议增加testlink2xmind功能；这样修改用例更加方便

**Comment by tobyqin** [comment]
这比想象中的复杂，我们的习惯是在xmind里编写，修改甚至执行，最后导入到testlink里归档。

**Comment by WinterDing** [comment]
@tobyqin 
xmind2testlink最初的又是我认为是结合testlink（项目管理，进度把控能力），xmind发散思维编写测试用例的能力
问题：
1）如果执行在xmind中做，如何把控测试进度？
我现在考虑的流程是这样的：
xmind编写某功能测试用例->通过评审后->落地到testlink中开始执行；中间测试用例的修改（增删改）在xmind中进行；这样最终版的测试用例是xmind的测试用例；->最终版测试用例导入testlink base测试用例库（所有功能模块的测试用例合集）；但是这样就会引出问题：
1）如果使用testlink来管理base测试用例库，测试用例后续的修改就需要在testlink里进行；（不能导出到xmind）
2）如果用xmind来管理base测试用例库，后期不同的人修改测试用例，如何协同工作？

问题较多，请帮忙回答；多谢


2）想请教，你们那里的最佳实践是什么？

**Comment by tobyqin** [comment]
@WinterDing 

1. xmind中执行测试主要是针对不大的需求，进度主要靠敏捷模型，比如2周一个sprint，每天例会会在看板前更新开发和测试状态，xmind里的进度口头汇报就好，上线后导入testlink归档。

2. 对于很大的需求我们会分工，准备案例，评审，导入，建立测试计划等等，可能会经历好几个sprint。在测试执行时不可避免会发现案例需要调整，直接从testlink改就好了，xmind就不管了。如果需要补case新建xmind用一样的结构写就好了。

3. 没有所谓的最佳实践，每个公司流程资源都不太一样，找到合适的感觉流畅的就行。testlink的case最好都是终版，xmind在过程中是工具的角色，用成你想要的样子。

BTW，testlink大家其实都不是太喜欢，但是又没有更好的替代方法，除了忍那么其实你们也可以尝试去做一些力所能及的改进。比如你说的从testlink导出xmind（试试无妨），再比如从xmind执行后把结果再导入test plan。再或者整个咱们心仪的testlink 😸

**Comment by tobyqin** [comment]
其实分析testlink导出的xml不算复杂，关键是没有很好的生成xmind的包，pip上有一个我感觉不太靠谱，现在还有zen的版本，里面格式也不一样，要解决的问题不少。

**Comment by WinterDing** [comment]
工具很棒，搭建了xmind和testlink之间的桥梁（痛点）；目前对我来说，优先级最高的是在已有框架下适配到我们公司的测试工作中；既能把控进度，同时可以更加高效地编织测试用例；
保持沟通哈。感觉有很多可以学习的
