### ISSUE TITLE
增加测试用例执行时间功能

### ISSUE THREAD

**Issue by WinterDing** [tobyqin/xmind2testlink#35]

**Comment by tobyqin** [comment]
请明示

**Comment by WinterDing** [comment]
对于每一条测试用例需要记录执行时间；testlink里可以记录, xmind是否可以增加该功能，然后通过xmind2testlink后直接反映到testlink中

**Comment by tobyqin** [comment]
xmind 里记在哪，拿什么形式记，要回答的是这个问题。
