### ISSUE TITLE
xmind2testlink是否支持中文呢

### ISSUE THREAD

**Issue by berrycam** [tobyqin/xmind2testlink#9]
首先非常感谢您的贡献，我在测试工具时发现不支持中文，请问如需要支持将xmind的中文文档转换为xml，我可以做些什么呢？

**Comment by tobyqin** [comment]
中文我没特别考虑，是否可以把错误信息和测试用的xmind附上？
有时间我会fix一下，附件你可以回复到这个issue。

**Comment by berrycam** [comment]
我在自己的安装目录（win7）：D:\Python27\Lib\site-packages\xmind2testlink，尝试对xmind_parser.py、testlink_parser.py中读取xmind，与写入xml时换一种编码方式，如GBK，并在本地重新编译后没成功。

非常感谢，我参考您的格式编写的用例，测试用例见附件：
[xmind2testlink支持中文.zip](https://github.com/tobyqin/xmind2testlink/files/1965797/xmind2testlink.zip)

辛苦Toby了，非常感谢您在百忙之中回复我，并帮忙解决问题，谢谢~

**Comment by berrycam** [comment]
此外，在执行xmind2testlink path/AA.xmind转换时，
情况1、如AA.xmind为英文+中文混合一起编写的，但是其中任意一个思维导图的节点包括中文或者中文标点符号，则该节点无法进行转换。
情况2：如AA.xmind为全部为英文编写的，导出的xml文件为空，即未生成。

**Comment by tobyqin** [comment]
@berrycam 我本机是Python3.5, 可以convert你给我的xmind，没有异常。
建议你升级一下Python，Python 2.x 再过1年就被彻底放弃了，你遇到的问题估计是编码相关的坑，我不打算装个2.7去debug，抱歉。

关于PY3和PY2的优缺点网上有很多比较，也可以参考我的博客：
- https://betacat.online/posts/2017-02-06/move-on-to-python-3/

**Comment by tobyqin** [comment]
如果你测试一定要Python2，也可以考虑并行安装一个Python3，然后把这个小工具安装到Python3的lib中，最后通过快捷方式或者配置PATH的方法来调用。

我一般还会在闲置的测试机器上部署一个web版本让其他人访问，你可以借鉴一下。

**Comment by berrycam** [comment]
@tobyqin 您分享的工具非常好用，谢谢你回复我的问题。

我自己来按您提供的方案来解决吧。我安装的环境是python2.7，上周还发现无法安装Arrow库，当时怀疑是不是我的python版本支持问题，现正好解决此问题，卸载重新安装python 3，可以解决xmind中文的问题就好，然后部署起来并应用。

我现在应用也没有一定要用python2，正在学习阶段，所以应用相对较广泛的python2，多谢指点。

**Comment by berrycam** [comment]
可能是初学者啊，在摸索中学习，比较保守，正好有此契机切换至Python3上学习。

**Comment by tobyqin** [comment]
互相学习，不客气。
